name: git-artifacts

on:
  repository_dispatch:
    types:
      - git-artifacts

env:
  GIT_CONFIG_PARAMETERS: "'user.name=${{github.actor}}' 'user.email=${{github.actor}}@users.noreply.github.com' 'user.signingkey=mine'"
  GPG_OPTIONS: "--batch --yes --no-tty --list-options no-show-photos --verify-options no-show-photos --pinentry-mode loopback"
  HOME: "${{github.workspace}}\\home"
  MSYSTEM: MINGW64
  PACKAGER: ${{github.actor}} <${{github.actor}}@users.noreply.github.com>
  USERPROFILE: "${{github.workspace}}\\home"
  BUILD_ONLY: "${{github.event.client_payload.build_only}}"
  REPOSITORY: "${{github.event.client_payload.repository}}"
  REF: "${{github.event.client_payload.ref}}"

jobs:
  bundle-artifacts:
    runs-on: windows-latest
    steps:
      - name: Download git-sdk-64-build-installers
        shell: bash
        run: |
          a=git-sdk-64-build-installers && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf - &&
          mkdir -p home &&
          git config --global windows.sdk32.path '' &&
          git config --global windows.sdk64.path "$PWD/$a"
      - name: Clone build-extra
        run: git clone --single-branch -b master https://github.com/git-for-windows/build-extra git-sdk-64-build-installers\usr\src\build-extra
      - name: Prepare home directory for GPG signing
        if: env.GPGKEY != '' && env.PRIVGPGKEY != ''
        shell: bash
        run: |
          echo '$PRIVGPGKEY' | tr % '\\n' | gpg $env:GPG_OPTIONS --import &&
          mkdir -p home &&
          git config --global gpg.program "$PWD/git-sdk-64/usr/src/build-extra/gnupg-with-gpgkey.sh"
        env:
          PRIVGPGKEY: ${{secrets.PRIVGPGKEY}}
      - name: Generate bundle artifacts
        env:
          GPGKEY: ${{secrets.GPGKEY}}
        shell: powershell
        run: |
          & .\git-sdk-64-build-installers\git-cmd.exe --command=usr\bin\bash.exe -lc @"
            printf '#!/bin/sh\n\nexec /mingw64/bin/git.exe "`$@"\n' >/usr/bin/git &&
            mkdir -p bundle-artifacts &&

            { test -n \"`$REPOSITORY\" || REPOSITORY='${{github.repository}}'; } &&
            { test -n \"`$REF\" || REF='${{github.ref}}'; } &&
            git init --bare &&
            git remote add -f origin https://github.com/git-for-windows/git &&
            git fetch \"https://github.com/`$REPOSITORY\" \"`$REF:`$REF\" &&

            tag_name=\"`$(git describe --match 'v[0-9]*' FETCH_HEAD)-`$(date +%Y%m%d%H%M%S)\" &&
            echo \"prerelease-`${tag_name#v}\" >bundle-artifacts/ver &&
            echo \"`${tag_name#v}\" >bundle-artifacts/display_version &&
            echo \"`$tag_name\" >bundle-artifacts/next_version &&
            git tag `$(test -z \"`$GPGKEY\" || echo \" -s\") -m \"Snapshot build\" \"`$tag_name\" FETCH_HEAD &&
            git bundle create bundle-artifacts/git.bundle origin/master..\"`$tag_name\" &&

            sh -x /usr/src/build-extra/please.sh mention feature \"Snapshot of `$(git show -s  --pretty='tformat:%h (%s, %ad)' --date=short FETCH_HEAD)\" &&
            git -C /usr/src/build-extra bundle create \"`$PWD/bundle-artifacts/build-extra.bundle\" origin/master..master
          "@
      - name: Clean up temporary files
        if: always()
        shell: bash
        run: rm -rf home
      - name: 'Publish Pipeline Artifact: bundle-artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
  pkg:
    runs-on: windows-latest
    needs: bundle-artifacts
    strategy:
      matrix:
        arch:
          - name: x86_64
            bitness: 64
            bin: /amd64
          - name: i686
            bitness: 32
            bin: ''
    steps:
      - name: Download git-sdk-64-makepkg-git
        shell: bash
        run: a=git-sdk-64-makepkg-git && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf -
      - name: Download bundle-artifacts
        uses: actions/download-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
      - name: Check out build-extra/git and git/git
        run: |
          .\git-sdk-64-makepkg-git\usr\bin\bash.exe -lc @"
            git clone --depth=10 --single-branch -b master https://github.com/git-for-windows/build-extra /usr/src/build-extra &&
            git -C /usr/src/build-extra pull \"`$PWD\"/bundle-artifacts/build-extra.bundle master &&

            set -x &&
            git init &&
            git remote add -f origin https://github.com/git-for-windows/git &&
            git fetch --tags bundle-artifacts/git.bundle `$(cat bundle-artifacts/next_version) &&
            git reset --hard `$(cat bundle-artifacts/next_version)
          "@
      - name: Prepare home directory for code-signing
        env:
          CODESIGN_P12: ${{secrets.CODESIGN_P12}}
          CODESIGN_PASS: ${{secrets.CODESIGN_PASS}}
        if: env.CODESIGN_P12 != '' && env.CODESIGN_PASS != ''
        shell: bash
        run: |
          cd home &&
          mkdir -p .sig &&
          echo "$CODESIGN_P12" | tr % '\n' | base64 -d >.sig/codesign.p12 &&
          echo "$CODESIGN_PASS" >.sig/codesign.pass
          git config --global alias.signtool '!sh "/usr/src/build-extra/signtool.sh"'
      - name: Prepare home directory for GPG signing
        if: env.GPGKEY != '' && env.PRIVGPGKEY != ''
        shell: bash
        run: echo '$PRIVGPGKEY' | tr % '\\n' | gpg $env:GPG_OPTIONS --import
        env:
          PRIVGPGKEY: ${{secrets.PRIVGPGKEY}}
      - name: Build mingw-w64-${{matrix.arch.name}}-git
        env:
          GPGKEY: "${{secrets.GPGKEY}}"
        shell: powershell
        run: |
          & git-sdk-64-makepkg-git\usr\bin\sh.exe -lc @"
            set -x
            # Let `cv2pdb` find the DLLs
            PATH=\"`$PATH:/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin${{matrix.arch.bin}}\"
            type -p mspdb140.dll || exit 1
            sh -x /usr/src/build-extra/please.sh build-mingw-w64-git --only-${{matrix.arch.bitness}}-bit --build-src-pkg -o artifacts HEAD &&
            cp bundle-artifacts/ver artifacts/ &&
            if test -n \"`$GPGKEY\"
            then
              for tar in artifacts/*.tar*
              do
                /usr/src/build-extra/gnupg-with-gpgkey.sh --detach-sign --no-armor `$tar
              done
            fi &&

            b=`$PWD/artifacts &&
            version=`$(cat bundle-artifacts/next_version) &&
            (cd /usr/src/MINGW-packages/mingw-w64-git &&
            cp PKGBUILD.`$version PKGBUILD &&
            git commit -s -m \"mingw-w64-git: new version (`$version)\" PKGBUILD &&
            git bundle create \"`$b\"/MINGW-packages.bundle origin/master..master)
          "@
      - name: Clean up temporary files
        if: always()
        shell: bash
        run: rm -rf home
      - name: Publish mingw-w64-${{matrix.arch.name}}-git
        uses: actions/upload-artifact@v1
        with:
          name: pkg-${{matrix.arch.name}}
          path: artifacts
  artifacts:
    runs-on: windows-latest
    needs: pkg
    strategy:
      matrix:
        artifact:
          - name: installer
          - name: portable
            fileprefix: PortableGit
            fileextension: exe
          - name: archive
            fileprefix: Git
            fileextension: tar.bz2
          - name: mingit
            fileprefix: MinGit
            fileextension: zip
          - name: mingit-busybox
            fileprefix: MinGit
            fileextension: zip
        arch:
          - name: x86_64
            bitness: 64
          - name: i686
            bitness: 32
      fail-fast: false
    env:
      MSYSTEM: MINGW${{matrix.arch.bitness}}
    steps:
      - name: Determine whether this job should be skipped
        shell: python
        run: |
          import os
          if ("BUILD_ONLY" in os.environ) and len([x for x in os.environ["BUILD_ONLY"].split(",") if "${{matrix.artifact.name}}-${{matrix.arch.name}}".startswith(x)]) == 0:
            print("::set-env name=SKIP::true")
      - name: Download pkg-${{matrix.arch.name}}
        if: env.SKIP != 'true'
        uses: actions/download-artifact@v1
        with:
          name: pkg-${{matrix.arch.name}}
          path: pkg-${{matrix.arch.name}}
      - name: Download bundle-artifacts
        if: env.SKIP != 'true'
        uses: actions/download-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
      - name: Download git-sdk-${{matrix.arch.bitness}}-build-installers
        if: env.SKIP != 'true'
        shell: bash
        run: a=git-sdk-${{matrix.arch.bitness}}-build-installers && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf -
      - name: Clone build-extra
        if: env.SKIP != 'true'
        run: git clone --single-branch -b master https://github.com/git-for-windows/build-extra git-sdk-${{matrix.arch.bitness}}-build-installers\usr\src\build-extra
      - name: Prepare home directory for code-signing
        env:
          CODESIGN_P12: ${{secrets.CODESIGN_P12}}
          CODESIGN_PASS: ${{secrets.CODESIGN_PASS}}
        if: env.SKIP != 'true' && (matrix.artifact.name == 'installer' || matrix.artifact.name == 'portable') && env.CODESIGN_P12 != '' && env.CODESIGN_PASS != ''
        shell: bash
        run: |
          mkdir -p home/.sig &&
          echo "$CODESIGN_P12" | tr % '\n' | base64 -d >home/.sig/codesign.p12 &&
          echo "$CODESIGN_PASS" >home/.sig/codesign.pass &&
          git config --global alias.signtool '!sh "/usr/src/build-extra/signtool.sh"'
      - name: Build ${{matrix.arch.bitness}}-bit ${{matrix.artifact.name}}
        if: env.SKIP != 'true'
        shell: powershell
        run: |
          & .\git-sdk-${{matrix.arch.bitness}}-build-installers\usr\bin\bash.exe -lc @"
            set -x
            /usr/src/build-extra/please.sh make_installers_from_mingw_w64_git --version=`$(cat pkg-${{matrix.arch.name}}/ver) -o artifacts --${{matrix.artifact.name}} --pkg=pkg-${{matrix.arch.name}}/mingw-w64-${{matrix.arch.name}}-git-[0-9]*.tar.xz --pkg=pkg-${{matrix.arch.name}}/mingw-w64-${{matrix.arch.name}}-git-doc-html-[0-9]*.tar.xz &&
            if test portable = '${{matrix.artifact.name}}' && test -n \"`$(git config alias.signtool)\"
            then
              git signtool artifacts/PortableGit-*.exe
            fi &&
            openssl dgst -sha256 artifacts/${{matrix.artifact.fileprefix}}-*.${{matrix.artifact.fileextension}} | sed \"s/.* //\" >artifacts/sha-256.txt
          "@
      - name: Copy package-versions and pdbs
        if: env.SKIP != 'true' && matrix.artifact.name == 'installer'
        shell: powershell
        run: |
          & .\git-sdk-${{matrix.arch.bitness}}-build-installers\usr\bin\bash.exe -lc @"
            cp /usr/src/build-extra/installer/package-versions.txt artifacts/ &&

            a=`$PWD/artifacts &&
            p=`$PWD/pkg-${{matrix.arch.name}} &&
            (cd /usr/src/build-extra &&
            mkdir -p cached-source-packages &&
            cp \"`$p\"/*-pdb* cached-source-packages/ &&
            GIT_CONFIG_PARAMETERS=\"'windows.sdk${{matrix.arch.bitness}}.path='\" ./please.sh bundle_pdbs --arch=${{matrix.arch.name}} --directory=\"`$a\" installer/package-versions.txt)
          "@
      - name: Clean up temporary files
        if: always() && env.SKIP != 'true'
        shell: bash
        run: rm -rf home
      - name: Publish ${{matrix.artifact.name}}-${{matrix.arch.name}}
        if: env.SKIP != 'true'
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.artifact.name}}-${{matrix.arch.name}}
          path: artifacts
  nuget:
    runs-on: windows-latest
    needs: pkg
    steps:
      - name: Determine whether this job should be skipped
        shell: python
        run: |
          import os
          if ("BUILD_ONLY" in os.environ) and len([x for x in os.environ["BUILD_ONLY"].split(",") if "nuget-x86_64".startswith(x)]) == 0:
            print("::set-env name=SKIP::true")
      - name: Download pkg-x86_64
        if: env.SKIP != 'true'
        uses: actions/download-artifact@v1
        with:
          name: pkg-x86_64
          path: pkg-x86_64
      - name: Download bundle-artifacts
        if: env.SKIP != 'true'
        uses: actions/download-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
      - name: Download git-sdk-64-build-installers
        if: env.SKIP != 'true'
        shell: bash
        run: a=git-sdk-64-build-installers && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf -
      - name: Clone build-extra
        if: env.SKIP != 'true'
        run: git clone --single-branch -b master https://github.com/git-for-windows/build-extra git-sdk-64-build-installers\usr\src\build-extra
      - uses: nuget/setup-nuget@v1
        if: env.SKIP != 'true'
      - name: Build 64-bit NuGet packages
        if: env.SKIP != 'true'
        shell: powershell
        run: |
          & .\git-sdk-64-build-installers\usr\bin\bash.exe -lc @"
            set -x
            # Update the release notes
            git -C /usr/src/build-extra pull \"`$PWD\"/bundle-artifacts/build-extra.bundle master &&
            /usr/src/build-extra/please.sh make_installers_from_mingw_w64_git --version=`$(cat pkg-x86_64/ver) -o artifacts --nuget --pkg=pkg-x86_64/mingw-w64-x86_64-git-[0-9]*.tar.xz --pkg=pkg-x86_64/mingw-w64-x86_64-git-doc-html-[0-9]*.tar.xz &&
            /usr/src/build-extra/please.sh make_installers_from_mingw_w64_git --version=`$(cat pkg-x86_64/ver) -o artifacts --nuget-mingit &&
            openssl dgst -sha256 artifacts/Git*.nupkg | sed \"s/.* //\" >artifacts/sha-256.txt
          "@
      - name: Publish nuget-x86_64
        if: env.SKIP != 'true'
        uses: actions/upload-artifact@v1
        with:
          name: nuget-x86_64
          path: artifacts
